spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client-7001


server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名
    #hostname: eureka7001.com #eureka集群的时候，在hosts中配置127.0.0.1映射
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #（单机）设置与eureka server交互地址查询和注册服务都要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client-7001

server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名
    #hostname: eureka7001.com #eureka集群的时候，在hosts中配置127.0.0.1映射
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #（单机）设置与eureka server交互地址查询和注册服务都要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka



